"""add caretaker_id to users for patient relationship

Revision ID: 143d8fead764
Revises: d49c18cb7c6f
Create Date: 2026-07-23 15:42:49.945069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143d8fead764'
down_revision: Union[str, Sequence[str], None] = 'd49c18cb7c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('caretaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['caretaker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'caretaker_id')
    # ### end Alembic commands ###
