"""add caretaker_id to users

Revision ID: 770a5b3a37bf
Revises: 6dc3e68fb9fb
Create Date: 2026-08-15 15:58:33.265398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770a5b3a37bf'
down_revision: Union[str, Sequence[str], None] = '6dc3e68fb9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_invites_email'), table_name='patient_invites')
    op.drop_index(op.f('ix_patient_invites_id'), table_name='patient_invites')
    op.drop_index(op.f('ix_patient_invites_token'), table_name='patient_invites')
    op.drop_table('patient_invites')
    op.add_column('users', sa.Column('caretaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['caretaker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'caretaker_id')
    op.create_table('patient_invites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('caretaker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.id'], name=op.f('patient_invites_caretaker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_invites_pkey'))
    )
    op.create_index(op.f('ix_patient_invites_token'), 'patient_invites', ['token'], unique=True)
    op.create_index(op.f('ix_patient_invites_id'), 'patient_invites', ['id'], unique=False)
    op.create_index(op.f('ix_patient_invites_email'), 'patient_invites', ['email'], unique=False)
    # ### end Alembic commands ###
